name: widgets_to_image
description: A powerful Flutter package to convert any widget into high-quality images with customizable formats, quality settings, and advanced features.
version: 2.0.1
homepage: https://github.com/MohamedAbd0/widgets_to_image
repository: https://github.com/MohamedAbd0/widgets_to_image
issue_tracker: https://github.com/MohamedAbd0/widgets_to_image/issues
documentation: https://github.com/MohamedAbd0/widgets_to_image#readme

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
